version: '3'

volumes:
  db-data:
  uploads:

services:
  database:
    image: mongo:4.4
    container_name: mongo4
    volumes:
      - db-data:/data/db
    restart: always
    ports:
      - '27017:27017'

  agenda-back:
    build: ./
    container_name: agenda-back
    depends_on:
      - database
    restart: always
    volumes:
      - uploads:/agenda-back/src/uploads
    ports:
      - '80:80'
